---
title: "COVID-19 Vaccine Efficacy"
author: "Andrew Kostandy"
date: "18/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(rstan)
library(ggplot2)
library(bayesplot)
options(mc.cores = parallel::detectCores()-2)
```

```{r, message=FALSE, warning=FALSE, results='hide'}
# The Stan model as a string.
model_string <- "
data {
// Moderna
  int moderna_vacc_n1; // Number of trials - vaccine
  int moderna_vacc_s1; // Number of infections - vaccine
  
  int moderna_plac_n2; // Number of trials - placebo
  int moderna_plac_s2; // Number of infections - placebo
  
// Pfizer
  int pfizer_vacc_n1; // Number of trials - vaccine
  int pfizer_vacc_s1; // Number of infections - vaccine
  
  int pfizer_plac_n2; // Number of trials - placebo
  int pfizer_plac_s2; // Number of infections - placebo
}


parameters {

// Moderna
  real<lower=0, upper=1> moderna_vacc_rate1;
  real<lower=0, upper=1> moderna_plac_rate2;

// Pfizer
  real<lower=0, upper=1> pfizer_vacc_rate1;
  real<lower=0, upper=1> pfizer_plac_rate2;
}


model {

// Moderna
  moderna_vacc_rate1 ~ uniform(0, 1);
  moderna_vacc_s1 ~ binomial(moderna_vacc_n1, moderna_vacc_rate1);
  
  moderna_plac_rate2 ~ uniform(0,1);
  moderna_plac_s2 ~ binomial(moderna_plac_n2, moderna_plac_rate2);

// Pfizer
  pfizer_vacc_rate1 ~ uniform(0, 1);
  pfizer_vacc_s1 ~ binomial(pfizer_vacc_n1, pfizer_vacc_rate1);
  
  pfizer_plac_rate2 ~ uniform(0,1);
  pfizer_plac_s2 ~ binomial(pfizer_plac_n2, pfizer_plac_rate2);
}


generated quantities {
  real moderna_vaccine_efficacy;
  real pfizer_vaccine_efficacy;
  moderna_vaccine_efficacy = 1-((moderna_vacc_rate1*moderna_vacc_n1) / (moderna_plac_rate2*moderna_plac_n2));
  pfizer_vaccine_efficacy = 1-((pfizer_vacc_rate1*pfizer_vacc_n1) / (pfizer_plac_rate2*pfizer_plac_n2));
}
"

data_list <- list(moderna_vacc_n1 = 15000, moderna_vacc_s1 = 5, moderna_plac_n2 = 15000, moderna_plac_s2 = 90,
                  pfizer_vacc_n1 = 21769, pfizer_vacc_s1 = 8, pfizer_plac_n2 = 21769, pfizer_plac_s2 = 162)

# Compiling and producing posterior samples from the model.
set.seed(2020)
stan_samples <- stan(model_code = model_string, data = data_list, iter = 8000)
```

```{r}
traceplot(stan_samples)
```

```{r}
# Export the samples to a data.frame.
posterior <- as.data.frame(stan_samples)
head(posterior)
```

```{r, message=FALSE, fig.width=6}
mcmc_intervals(posterior,
  pars = c("pfizer_vaccine_efficacy", "moderna_vaccine_efficacy"),
  prob = 0.5,
  prob_outer = 0.9,
  point_est = "median"
) +
  scale_x_continuous(breaks = seq(0, 1, 0.01), labels = scales::percent_format(accuracy = 1)) +
  scale_y_discrete(labels = c("Pfizer/\nBioNTech\n(8:162)\n(n=43,538)", "Moderna\n(5:90)\n(n=30,000)")) +
  labs(
    title = "COVID-19 Vaccine Efficacy Rates Estimation for Moderna & Pfizer/BioNTech (Posterior Distributions)",
    subtitle = paste0(
      "Dark blue lines show 50% credible intervals",
      "\nLight blue lines show 90% credible intervals",
      "\nPoints show median values"
    ),
    caption = paste0(
      "Based on a Bayesian model using an uninformative uniform prior of rate & a binomial likelihood for the data.",
      "\nModel fit with Stan using Hamiltonian MCMC.",
      "\nEqual split of subject number (n) between vaccine & placebo groups assumed.",
      "\nData sources: https://bit.ly/3pFiAhV     https://bit.ly/2HdGXSD     https://bit.ly/3nAsyzs",
      "\nCode: https://bit.ly/32WDn6N",
      "\nCreated by: Andrew Kostandy"
    )
  ) +
  theme(text = element_text(size = 15), plot.caption = element_text(hjust = 0))
```

```{r}
ggsave("mcmc_intervals.pdf", dpi = "retina", width = 12, height = 8)
```

```{r, message=FALSE, fig.width=6}
mcmc_areas(
  posterior,
  pars = c("pfizer_vaccine_efficacy", "moderna_vaccine_efficacy"),
  prob = 0.95,
  prob_outer = 1,
  point_est = "median"
) +
  scale_x_continuous(breaks = seq(0, 1, 0.02), labels = scales::percent_format(accuracy = 1)) +
  scale_y_discrete(labels = c("Pfizer/\nBioNTech\n(8:162)\n(n=43,538)", "Moderna\n(5:90)\n(n=30,000)")) +
  labs(
    title = "COVID-19 Vaccine Efficacy Rates Estimation for Moderna & Pfizer/BioNTech (Posterior Distributions)",
    subtitle = paste0(
      "Shaded regions show 95% credible intervals",
      "\nSolid lines show median values"
    ),
    caption = paste0(
      "Based on a Bayesian model using an uninformative uniform prior of rate & a binomial likelihood for the data.",
      "\nModel fit with Stan using Hamiltonian MCMC.",
      "\nEqual split of subject number (n) between vaccine & placebo groups assumed.",
      "\nData sources: https://bit.ly/3pFiAhV     https://bit.ly/2HdGXSD     https://bit.ly/3nAsyzs",
      "\nCode: https://bit.ly/32WDn6N",
      "\nCreated by: Andrew Kostandy"
    )
  ) +
  theme(text = element_text(size = 15), plot.caption = element_text(hjust = 0))
```

```{r}
ggsave("mcmc_areas.pdf", dpi = "retina", width = 12, height = 8)
```


```{r}
# Probability Pfizer's vaccine has a higher efficacy than Moderna's
mean(posterior$pfizer_vaccine_efficacy>posterior$moderna_vaccine_efficacy)
```





